### ISSUE TITLE
column user_id not found

### ISSUE THREAD

**Issue by nadar** [luyadev/luya-module-admin#551]
yii\base\ErrorException
Undefined index: user_id
/var/www/html/releases/20200811144447/vendor/yiisoft/yii2/db/ActiveRelationTrait.php in handleError at line 526

(https://github.com/yiisoft/yii2/blob/master/framework/db/ActiveRelationTrait.php#L526)

```
        $values = [];
        if (count($attributes) === 1) {
            // single key
            $attribute = reset($this->link);
            foreach ($models as $model) {
                if (($value = $model[$attribute]) !== null) {
                    if (is_array($value)) {
                        $values = array_merge($values, $value);
                    } elseif ($value instanceof ArrayExpression && $value->getDimension() === 1) {
                        $values = array_merge($values, $value->getValue());
                    } else {
                        $values[] = $value;
```

in

```php
UserOnline::find()
                ->select(['lock_pk', 'lock_table', 'last_timestamp', 'firstname', 'lastname', 'admin_user.id'])
                ->where(['!=', 'admin_user.id', $userId])
                ->joinWith('user')
                ->asArray()
                ->all(),
```

The fix seems to be "obvious" but the error is only occurring on that specific server with an Amazon RDS connection with the given mode:

```
ALLOW_INVALID_DATES, ANSI, ANSI_QUOTES, DB2, ERROR_FOR_DIVISION_BY_ZERO, HIGH_NOT_PRECEDENCE, IGNORE_BAD_TABLE_OPTIONS, IGNORE_SPACE, MAXDB, MSSQL, MYSQL323, MYSQL40, NO_AUTO_CREATE_USER, NO_AUTO_VALUE_ON_ZERO, NO_BACKSLASH_ESCAPES, NO_DIR_IN_CREATE, NO_ENGINE_SUBSTITUTION, NO_FIELD_OPTIONS, NO_KEY_OPTIONS, NO_TABLE_OPTIONS, NO_UNSIGNED_SUBTRACTION, NO_ZERO_DATE, NO_ZERO_IN_DATE, ONLY_FULL_GROUP_BY, ORACLE, PAD_CHAR_TO_FULL_LENGTH, PIPES_AS_CONCAT, POSTGRESQL, REAL_AS_FLOAT, STRICT_ALL_TABLES, STRICT_TRANS_TABLES, TRADITIONAL
```

**Comment by nadar** [comment]
I am still unable to reproduce the error local.

+ try with sql strict mode (see config below)
+ ensuring all errors are thrown https://github.com/luyadev/luya-docker-php/blob/master/custom.ini
+ disabled caching of schemas

strict mode docker compose config:

```
luya_db:
    image: mariadb:10.1.34
    command:
      - --sql-mode=STRICT_TRANS_TABLES
      - --character-set-server=utf8
      - --collation-server=utf8_general_ci
    environment:
      MYSQL_ROOT_PASSWORD: luya
      MYSQL_DATABASE: vertikal
      MYSQL_USER: luya
      MYSQL_PASSWORD: luya
```
