### ISSUE TITLE
Roboto font has only latin subset

### ISSUE THREAD

**Issue by nick-denry** [luyadev/luya-module-admin#80]
Hi!

Roboto font included in [admin.css](https://github.com/luyadev/luya-module-admin/blob/master/src/resources/dist/css/admin.css) has only latin language subset so doesn't applied for another languages (fall-back system sans-serif font applied).

i.e. roboto-v16-latin-100.eot

```css
@font-face {
    font-family: 'Roboto';
    font-style: normal;
    font-weight: 100;
    src: url("../../fonts/roboto/roboto-v16-latin-100.eot");
    src: local("Roboto Thin"), local("Roboto-Thin"), url("../../fonts/roboto/roboto-v16-latin-100.eot?#iefix") format("embedded-opentype"), url("../../fonts/roboto/roboto-v16-latin-100.woff2") format("woff2"), url("../../fonts/roboto/roboto-v16-latin-100.woff") format("woff"), url("../../fonts/roboto/roboto-v16-latin-100.ttf") format("truetype"), url("../../fonts/roboto/roboto-v16-latin-100.svg#Roboto") format("svg")
}
```

Default `roboto`:

![2018-04-02 23 39 32](https://user-images.githubusercontent.com/1450983/38215062-2aa958de-36cf-11e8-82a7-2748234c9368.png)

Cyrillic subset `roboto`:

![2018-04-02 23 40 50](https://user-images.githubusercontent.com/1450983/38215092-4d1b6f24-36cf-11e8-9fac-a015daf579c8.png)

I've included subset via add it to [Main.php](https://github.com/luyadev/luya-module-admin/blob/master/src/assets/Main.php) assets file, but I guess it should be a better way to customize this. 

How it could be done?
